# Generated by Django 2.2.3 on 2019-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20190929_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='dissapered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
