# Generated by Django 2.2.3 on 2019-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20190929_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Тут должно быть описание монстра.'),
        ),
    ]
