# Generated by Django 2.2.3 on 2019-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20190929_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, help_text='Название покемона на английском', max_length=200),
        ),
    ]
