# Generated by Django 2.2.3 on 2019-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20190930_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, help_text='Тут должно быть описание монстра.'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, help_text='Название покемона на японском', max_length=200),
        ),
    ]
