# Generated by Django 2.2.3 on 2019-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0022_auto_20190930_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='dissapered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
