# Generated by Django 2.2.3 on 2019-09-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0031_auto_20190930_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evoluion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='pokemon_entities.Pokemon'),
        ),
    ]
