# Generated by Django 2.2.3 on 2019-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0032_pokemon_next_evoluion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evoluion',
            new_name='next_evolution',
        ),
    ]
