# Generated by Django 2.2.3 on 2019-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0034_auto_20190930_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, help_text='Название покемона на английском', max_length=200, verbose_name='Покемон на английском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, help_text='Название покемона на японском', max_length=200, verbose_name='Покемон на японском'),
        ),
    ]
