# Generated by Django 2.2.3 on 2019-09-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0039_auto_20190930_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_ev', to='pokemon_entities.Pokemon', verbose_name='Следующая эволюция'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_ev', to='pokemon_entities.Pokemon', verbose_name='Предыдущая эволюция'),
        ),
    ]
