# Generated by Django 2.2.3 on 2019-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0047_pokemonelementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='pokemons',
            field=models.ManyToManyField(blank=True, related_name='pokemon_elements', to='pokemon_entities.Pokemon', verbose_name='Покемоны'),
        ),
    ]
