# Generated by Django 2.2.3 on 2019-10-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0048_auto_20191008_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonelementtype',
            old_name='title',
            new_name='name',
        ),
    ]
