# Generated by Django 2.2.3 on 2019-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0049_auto_20191008_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='pokemons',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='pokemon_entities.PokemonElementType', verbose_name='Стихии'),
        ),
    ]
