# Generated by Django 2.2.3 on 2019-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0051_auto_20191008_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='_pokemonelementtype_strong_against_+', to='pokemon_entities.PokemonElementType', verbose_name='Силен против'),
        ),
    ]
